String courseIdFromSelectedClasses(List<int> selectedClasses) {
  final sorted = List<int>.from(selectedClasses)..sort();
  switch (sorted.join(',')) {
    case '1': return 'N';
    case '2': return 'E';
    case '3': return 'A';
    case '1,2': return 'NE';
    case '2,3': return 'EA';
    case '1,2,3': return 'NEA';
    default: return 'NEA';
  }
}

// Subsection title → URL slug (part after course prefix, e.g. "kondensator_1.html").
// Format: https://50ohm.de/${course}_${_subsectionSlugs[title]}
const Map<String, String> _subsectionSlugs = {
  // Erste Schritte
  'Der erste Schritt':                            'erste_schritte.html',
  'Rufzeichen':                                   'rufzeichen.html',
  'Internationale Buchstabiertafel':              'buchstabiertafel.html',
  'Betriebsabwicklung':                           'betriebsabwicklung.html',
  'Das RST-System':                               'rst.html',
  'Ausbildungsfunkbetrieb':                       'ausbildungsfunk.html',
  'Offene Sprache':                               'offene_sprache.html',
  'Funkverkehr nur mit Funkamateuren':            'nur_mit_afu_stellen.html',
  'Gewerbliche Nutzung':                          'gewerblich.html',

  // Elektrische Schwingungen und Funkwellen
  'Frequenz':                                     'frequenz.html',
  'Sinusschwingung':                              'sinusschwingung.html',
  'Amplitude und Periode':                        'amplitude_periode.html',
  'Zehnerpotenzen':                               'zehnerpotenzen.html',
  'Funkwellen':                                   'funkwellen.html',
  'Wellenlänge':                                  'wellenlaenge.html',
  'Wellenlänge II':                               'wellenlaenge_2.html',
  'Wasserfalldiagramm':                           'wasserfall.html',
  'Frequenzspektrum':                             'frequenzspektrum.html',
  'Frequenzzuteilung':                            'frequenzzuteilung.html',
  'Amateurfunkbänder':                            'amateurfunkbaender.html',
  'Primärer und sekundärer Funkdienst':           'primaerer_sekundaerer_funkdienst.html',
  'IARU-Bandpläne':                               'iaru_bandplan.html',
  'IARU-Bandplan für 2 m':                        'iaru_bandplan_2m.html',
  'IARU-Bandplan für 70 cm':                      'iaru_bandplan_70cm.html',

  // Wellenausbreitung
  'Funkhorizont':                                 'funkhorizont.html',
  'Troposphärische Inversionsbildung':            'troposphaere.html',
  'Troposphäre II':                               'troposphaere_2.html',
  'Troposphäre III':                              'troposphaere_3.html',
  'Aurora I':                                     'aurora_1.html',
  'Aurora II':                                    'aurora_2.html',
  'Sporadic-E I':                                 'sporadic_e_1.html',
  'Sporadic-E II':                                'sporadic_e_2.html',
  'Sporadic-E III':                               'sporadic_e_3.html',
  'Ionosphäre':                                   'ionosphaere.html',
  'Ionosphäre II':                                'ionosphaere_2.html',
  'Ionosphäre III':                               'ionosphaere_3.html',
  'Tote Zone I':                                  'tote_zone_1.html',
  'Tote Zone II':                                 'tote_zone_2.html',
  'Fading':                                       'fading.html',
  'Sprungdistanz I':                              'sprungdistanz_1.html',
  'Sprungdistanz II':                             'sprungdistanz_2.html',
  'MUF und LUF':                                  'muf_luf_1.html',
  'MUF und LUF II':                               'muf_luf_2.html',
  'Bodenwelle':                                   'bodenwelle.html',
  'Greyline':                                     'greyline.html',
  'Mögel-Dellinger-Effekt':                       'moegel_dellinger_effekt.html',
  'Langer und kurzer Weg I':                      'langer_kurzer_weg_1.html',
  'Langer und kurzer Weg II':                     'langer_kurzer_weg_2.html',
  'Scatter':                                      'scatter.html',

  // Amateurfunkstationen
  'Aufbau von Rufzeichen':                        'rufzeichenaufbau.html',
  'Persönliche Rufzeichen':                       'persoenliche_rufzeichen.html',
  'Klubstationen':                                'klubstationen.html',
  'Ausbildungsrufzeichen':                        'ausbildungsrufzeichen.html',
  'Remote-Stationen':                             'remote_stationen.html',
  'Rufzeichenzusätze':                            'rufzeichenzusaetze.html',
  'Besondere Anlässe':                            'besondere_anlaesse.html',
  'Fernbediente und automatische Stationen':      'fernbediente_automatische_stationen.html',
  'Relaisfunkstellen':                            'relaisfunkstellen.html',
  'Baken':                                        'baken.html',
  'Linkstrecken':                                 'linkstrecken.html',
  'Satelliten':                                   'satelliten.html',
  'Exterritoriale Stationen':                     'exterritoriale_stationen.html',
  'Experimentelle Studien':                       'experimentelle_studien.html',

  // Internationaler Funkbetrieb
  'Internationale Landeskenner':                  'internationale_landeskenner.html',
  'ITU-Regionen':                                 'itu_regionen.html',
  'DX':                                           'dx.html',
  'Funken im Ausland':                            'funken_im_ausland.html',

  // Strom, Spannung, Widerstand, Leistung, Energie
  'Recht zum Selbstbau':                          'recht_zum_selbstbau.html',
  'Elektrische Spannung':                         'spannung.html',
  'Elektrischer Strom':                           'strom.html',
  'Gefahren durch elektrischen Strom':            'gefahren.html',
  'Leiter und Nichtleiter':                       'leiter_nichtleiter.html',
  'Stromkreis':                                   'stromkreis.html',
  'Physikalische Stromrichtung':                  'physikalische_stromrichtung.html',
  'Spannungsmessung':                             'spannungsmessung.html',
  'Strom messen':                                 'strommessung.html',
  'Strom- und Spannungsmessung II':               'strom_spannung_messung_2.html',
  'Strom- und Spannungsmessung III':              'strom_spannung_messung_3.html',
  'Zeigerinstrumente ablesen':                    'zeigerinstrumente_ablesen.html',
  'Spitzen- und Effektivwert':                    'spitze_effektiv_wert.html',
  'Oszilloskop I':                                'oszilloskop_1.html',
  'Oszilloskop II':                               'oszilloskop_2.html',
  'Ohmsches Gesetz':                              'ohmsches_gesetz.html',
  'Widerstandsfarbcode':                          'widerstandsfarbcode.html',
  'SMD-Widerstände':                              'widerstand_smd.html',
  'Leiterwiderstand':                             'leiterwiderstand.html',
  'Widerstandsmaterialien':                       'widerstand_materialien.html',
  'Widerstandstoleranzen':                        'widerstand_toleranz.html',
  'Heißleiter und Kaltleiter':                    'widerstand_ntc_ptc.html',
  'Halbleiter':                                   'halbleiter.html',
  'Leistung':                                     'leistung.html',
  'Leistung beim Wechselstrom':                   'wechselstrom_leistung.html',
  'Leistung II':                                  'leistung_2.html',
  'Dezibel I':                                    'dezibel_1.html',
  'Dezibel II':                                   'dezibel_2.html',
  'Ladung und Energie':                           'ladung_energie.html',
  'Schaltzeichen und Bauelemente':                'bauelemente.html',

  // Elektromagnetisches Feld
  'Elektrisches Feld':                            'e_feld.html',
  'Magnetisches Feld':                            'h_feld.html',
  'Elektromagnetisches Feld':                     'em_feld.html',

  // Bauelemente
  'Kondensator I':                                'kondensator_1.html',
  'Phase':                                        'phase.html',
  'Kondensator II':                               'kondensator_2.html',
  'Spule I':                                      'spule_1.html',
  'Spule II':                                     'spule_2.html',
  'Übertrager I':                                 'uebertrager_1.html',
  'Übertrager II':                                'uebertrager_2.html',
  'Diode I':                                      'diode_1.html',
  'Diode II':                                     'diode_2.html',
  'Transistor I':                                 'transistor_1.html',
  'Transistor II':                                'transistor_2.html',
  'Halbleiter II':                                'halbleiter_2.html',
  'Integrierte Schaltkreise':                     'integrierte_schaltkreise.html',

  // Reihen- und Parallelschaltung von Bauelementen
  'Widerstand in Reihen- und Parallelschaltung':              'reihe_parallel_widerstand.html',
  'Widerstandsnetzwerke I':                                   'reihe_parallel_widerstandsnetz_1.html',
  'Widerstandsnetzwerke II':                                  'reihe_parallel_widerstandsnetz_2.html',
  'Spannungsteiler I':                                        'spannungsteiler_1.html',
  'Spannungsteiler II':                                       'spannungsteiler_2.html',
  'Brückenschaltung':                                         'brueckenschaltung.html',
  'Kondensator in Reihen- und Parallelschaltung':             'reihe_parallel_kondensator.html',
  'Spule in Reihenschaltung':                                 'reihenschaltung_spule.html',
  'Reihen- und Parallelschaltung gemischter Bauelemente':     'reihe_parallel_gemischt.html',

  // Strom- und Spannungsversorgung
  'Spannungsquellen':                             'spannungsquelle.html',
  'Innenwiderstand':                              'innenwiderstand.html',
  'Netzgerät I':                                  'netzgeraet_1.html',
  'Batterien und Akkus':                          'batterien_und_akkus.html',
  'Akkus':                                        'akku.html',
  'Photovoltaik':                                 'photovoltaik.html',
  'Spannungswandler':                             'spannungswandler.html',
  'Gleichrichter I':                              'gleichrichter_1.html',
  'Gleichrichter II':                             'gleichrichter_2.html',
  'Brückengleichrichter':                         'brueckengleichrichter.html',
  'Vollweggleichrichter':                         'vollweggleichrichter.html',
  'Restwelligkeit':                               'restwelligkeit.html',
  'Schaltnetzteil I':                             'schaltnetzteil_1.html',
  'Schaltnetzteil II':                            'schaltnetzteil_2.html',
  'Spannungsstabilisierung':                      'spannungsstabilisierung.html',
  'Fernspeiseweiche':                             'fernspeiseweiche.html',
  'Sicherungen':                                  'sicherungen.html',

  // Grundlegende Schaltungen
  'Schwingkreis I':                               'schwingkreis_1.html',
  'Schwingkreis II':                              'schwingkreis_2.html',
  'Oszillatoren':                                 'oszillatoren.html',
  'Spannungsgesteuerter Oszillator (VCO)':        'oszillator_vco.html',
  'Temperaturkompensation von Oszillatoren':      'oszillator_tcxo_ocxo.html',
  'GPS-disziplinierter Oszillator':               'oszillator_gpsdo.html',
  'Spannungsstabilität von Oszillatoren':         'oszillator_spannungsstabilitaet.html',
  'Oszillatorschaltungen':                        'oszillator_schaltungen.html',
  'Direkte digitale Synthese':                    'oszillator_dds.html',
  'Phasenregelschleife (PLL)':                    'oszillator_pll.html',
  'Frequenzvervielfacher I':                      'frequenzvervielfacher_1.html',
  'Frequenzvervielfacher II':                     'frequenzvervielfacher_2.html',
  'Mischer':                                      'mischer.html',
  'Konverter und Transverter':                    'transverter_1.html',
  'Konverter und Transverter II':                 'transverter_2.html',
  'Verstärker':                                   'verstaerker.html',
  'Kollektorschaltung':                           'kollektorschaltung.html',
  'Emitterschaltung':                             'emitterschaltung.html',
  'Verstärkerklassen':                            'verstaerker_klasse.html',
  'Verstärkungsleistung':                         'verstaerkungsleistung.html',
  'Wirkungsgrad':                                 'verstaerker_wirkungsgrad.html',
  'Linearverstärker':                             'verstaerker_linearverstaerker.html',
  'Eigenschwingung':                              'verstaerker_eigenschwingung.html',
  'Begrenzung der Verstärkerbandbreite':          'verstaerker_begrenzung_bandbreite.html',

  // Modulation
  'Rauch- und Morsezeichen':                      'rauch_und_morsezeichen.html',
  'Unmodulierter Träger':                         'unmodulierter_traeger.html',
  'Amplitudenmodulation (AM)':                    'am.html',
  'Amplitudenmodulation (AM) II':                 'am_2.html',
  'Einseitenbandmodulation (SSB) I':              'ssb.html',
  'Einseitenbandmodulation (SSB) II':             'ssb_2.html',
  'Einseitenbandmodulation (SSB) III':            'ssb_3.html',
  'Frequenzmodulation (FM)':                      'fm.html',
  'Frequenzmodulation (FM) II':                   'fm_2.html',
  'Frequenzmodulation (FM) III':                  'fm_3.html',
  'Phasenmodulation (PM)':                        'pm.html',
  'Bandbreite':                                   'bandbreite.html',
  'Bandbreite II':                                'bandbreite_2.html',
  'Bandbreite III':                               'bandreite_3.html',
  'Modulationseinstellungen am Funkgerät':        'trxmodulation.html',
  'Dynamikkompressor I':                          'dynamik_kompressor_1.html',
  'Dynamikkompressor II':                         'dynamik_compressor_2.html',

  // Empfänger
  'Aufbau eines Empfängers':                      'aufbau_empfaenger.html',
  'Detektorempfänger':                            'detektorempfaenger.html',
  'Überlagerungsempfänger (Einfachsuper) I':      'ueberlagerungsempfaenger_einfachsuper_1.html',
  'Überlagerungsempfänger (Einfachsuper) II':     'ueberlagerungsempfaenger_einfachsuper_2.html',
  'Mischer II':                                   'mischer_2.html',
  'Spiegelfrequenzen':                            'spiegelfrequenzen.html',
  'Doppelüberlagerungsempfänger (Doppelsuper)':   'doppelueberlagerungsempfaenger_doppelsuper.html',
  'Trennschärfe I':                               'trennschaerfe_1.html',
  'Trennschärfe II':                              'trennschaerfe_2.html',
  'BFO I':                                        'bfo_1.html',
  'BFO II':                                       'bfo_2.html',
  'Inter- und Kreuzmodulation':                   'intermodulation_kreuzmodulation.html',
  'Begrenzerverstärker':                          'begrenzerverstaerker.html',
  'Vorverstärker und Dämpfungsglied':             'vorverstaerker_daempfungsglied.html',
  'Low Noise Block (LNB)':                        'low_noise_block.html',
  'S-Meter':                                      's_meter.html',
  'Dämpfungsglieder':                             'daempfungsglieder.html',
  'Automatische Verstärkerregelung (AGC) I':      'agc_1.html',
  'Automatische Verstärkerregelung (AGC) II':     'agc_2.html',
  'SNR und Rauschzahl':                           'snr_rauschzahl.html',
  'Rauschen':                                     'rauschen.html',
  'RIT':                                          'rit.html',
  'VOX':                                          'vox.html',
  'Squelch':                                      'squelch.html',
  'Squelch II':                                   'squelch_2.html',
  'Notch-Filter':                                 'notchfilter.html',
  'Rauschunterdrückung':                          'noise_reduction.html',
  'Demodulator':                                  'demodulator.html',
  'Frequenzmessung I':                            'frequenzmessung_1.html',
  'Frequenzmessung II':                           'frequenzmessung_2.html',
  'Frequenzgenauigkeit':                          'frequenzgenauigkeit.html',

  // Sender
  'Aufbau eines Senders':                         'aufbau_sender.html',
  'Modulatoren':                                  'modulatoren.html',
  'Nicht-sinusförmige Signale':                   'nicht_sinus_signale.html',
  'Leistungsverstärker':                          'leistungsvertaerker.html',
  'Parasitäre Schwingungen':                      'parasitaere_schwingungen.html',
  'ALC':                                          'alc.html',
  'Ausgangsleistung':                             'ausgangsleistung.html',
  'Senderausgangsleistung':                       'senderausgangsleistung.html',
  'Messungen am Sender':                          'sender_messungen.html',
  'Dummy-Load I':                                 'dummy_load_1.html',
  'Dummy-Load II':                                'dummy_load_2.html',
  'Unerwünschte Aussendungen I':                  'unerwuenschte_aussendungen_1.html',
  'Unerwünschte Aussendungen II':                 'unerwuenschte_aussendungen_2.html',
  'Unerwünschte Aussendungen III':                'unerwuenschte_aussendungen_3.html',
  'Elektromagnetische Verträglichkeit':           'elektromagnetische_vertraeglichkeit.html',
  'Störungen vermeiden':                          'stoerungen_vermeiden.html',
  'Störende Beeinflussung elektronischer Geräte I':   'stoerungen_elektronischer_geraete_1.html',
  'Störungen elektronischer Geräte II':               'stoerungen_elektronischer_geraete_2.html',
  'Störungen beim Empfang':                       'empfangsstoerungen.html',
  'Remote-Station':                               'remote_station.html',

  // Logbuch und QSL-Karten
  'Logbuch':                                      'logbuch.html',
  'QSL-Karten':                                   'qsl_karten.html',

  // Digitale Übertragungsverfahren
  'Binäres Zahlensystem':                         'binaer.html',
  'Morsetelegrafie':                              'morsetelegrafie.html',
  'Computersteuerung':                            'computersteuerung.html',
  'Funkfernschreiben':                            'funkfernschreiben.html',
  'Digimode per SSB':                             'digimode_ssb.html',
  '9600-Port':                                    '9600_port.html',
  'Übersteuerung':                                'digimod_uebersteuerung.html',
  'Automatische Empfangsberichte':                'automatische_empfangsberichte.html',
  'Digital Voice (DV)':                           'digital_voice.html',
  'Paketvermittelte Netzwerke':                   'paketvermittelte_netzwerke.html',
  'Amplituden- und Frequenzumtastung (ASK, FSK)': 'ask_fsk_afsk.html',
  'Phasenumtastung (PSK)':                        'psk.html',
  'Symbolumschaltung und Bandbreite':             'symbolumschaltung_bandbreite.html',
  'Mehrwertige Verfahren':                        'mehrwertige_verfahren.html',
  'Quadraturamplitudenmodulation (QAM)':          'qam.html',
  'Orthogonales Frequenzmultiplexverfahren (OFDM)': 'ofdm.html',
  'AFSK':                                         'afsk.html',
  'Datenübertragungsrate':                        'datenuebertragungsdrate.html',
  'Shannon-Hartley-Gesetz':                       'shannon_hartley_gesetzt.html',
  'Quellencodierung':                             'quellencodierung.html',
  'Kanalcodierung':                               'kanalcodierung.html',
  'Fehlererkennung':                              'fehlererkennung.html',
  'Fehlerkorrektur':                              'fehlerkorrektur.html',
  'Sende- und Empfangsketten':                    'sende_empfangsketten.html',
  'Vielfachzugriff':                              'vielfachzugriff.html',
  'Synchronization':                              'synchronisation.html',

  // Abkürzungen
  'Betriebliche Abkürzungen':                     'betriebliche_abkuerzungen.html',
  'Q-Schlüssel':                                  'q_schluessel.html',
  'Maidenhead Locator':                           'locator.html',

  // Digitale Signalverarbeitung
  'Digitale Signalverarbeitung':                  'digitale_signalverarbeitung_einleitung.html',
  'Sampling und Quantisierung':                   'sampling_quantisierung.html',
  'Sampling':                                     'sampling.html',
  'Abtasttheorem':                                'abtasttheorem.html',
  'Quantisierung':                                'quantisierung.html',
  'Analog-Digital-Umsetzer (ADC)':                'analog_digital_umsetzer.html',
  'Digital-Analog-Umsetzer (DAC)':                'digital_analog_umsetzer.html',
  'Anwendung von ADC und DAC':                    'anwendung_dac_adc.html',
  'Anti-Alias-Filter':                            'anti_alias_filter.html',
  'Rekonstruktionsfilter':                        'rekonstruktionsfilter.html',
  'Fourier-Transformation':                       'fourier_transformation.html',
  'Digitale Filter':                              'digitale_filter.html',
  'I/Q-Verfahren':                                'iq_verfahren.html',
  'Latenz':                                       'latenz.html',

  // Betriebsabwicklung (chapter-level, not "Betriebsabwicklung" subsection above)
  'Pile-up':                                      'pileup.html',
  'Split-Verkehr':                                'split_betrieb.html',
  'Contest':                                      'contest.html',
  'Fuchsjagd (ARDF)':                             'ardf.html',
  'SSTV':                                         'sstv.html',
  'Notfunk':                                      'notfunk.html',

  // Antennen und Übertragungsleitungen
  'Antennen':                                     'antennen.html',
  'Dipol-Antenne':                                'dipol.html',
  'Yagi-Uda-Antenne I':                           'yagi_uda_1.html',
  'Rundstrahlantennen':                           'rundstrahler.html',
  'Endgespeiste Antennen (End-Fed)':              'endgespeiste_antennen.html',
  'Polarisation':                                 'polarisation.html',
  'Polarisation II':                              'polarisation_2.html',
  'Polarisation III':                             'polarisation_3.html',
  'Antennenformen II':                            'antennenformen_2.html',
  'Antennenformen III':                           'antennenformen_3.html',
  'Antennenlänge und -resonanz':                  'antenne_laenge_resonanz.html',
  'Verkürzungsfaktor I':                          'verkuerzungsfaktor_1.html',
  'Verkürzungsfaktor II':                         'verkuerzungsfaktor_2.html',
  'Fußpunktimpedanz I':                           'fusspunktimpedanz_1.html',
  'Fußpunktimpedanz II':                          'fusspunktimpedanz_2.html',
  'Elektrische Verlängerung und Verkürzung':      'elektrische_verlaengerung_verkuerzung.html',
  'Near Vertical Incidence Skywave (NVIS)':       'nvis.html',
  'Traps':                                        'traps.html',
  'Yagi-Uda Antenne II':                          'yagi_uda_2.html',
  'Yagi-Uda-Antenne III':                         'yagi_uda_3.html',
  'Parabolspiegel I':                             'parabolspiegel_1.html',
  'Parabolspiegel II':                            'parbolspiegel_2.html',
  'Offset-Spiegel':                               'offsetspiegel.html',
  'Vor-/Rückverhältnis':                          'vor_rueck_verhaeltnis.html',
  'Halbwertsbreite':                              'halbwertsbreite.html',
  'Strom- und Spannungsspeisung I':               'strom_spannung_speisung_1.html',
  'Strom- und Spannungsspeisung II':              'strom_spannung_speisung_2.html',
  'Frequenzabhängige Stromverteilung':            'frequenzabhaengige_stromverteilung.html',
  'Antennengewinn in dBi und dBd':               'antennengewinn.html',
  'Standortwahl':                                 'standortwahl.html',
  'Einbau Kfz':                                   'einbau_kfz.html',
  'Übertragungsleitungen':                        'uebertragungsleitungen.html',
  'Übertragungsleitungen II':                     'uebertragungsleitungen_2.html',
  'Übertragungsleitungen III':                    'uebertragungsleitungen_3.html',
  'Wellenwiderstand':                             'wellenwiderstand.html',
  'PL-Steckverbinder':                            'steckverbinder_pl.html',
  'N-Steckverbinder':                             'steckverbinder_n.html',
  'BNC-Steckverbinder':                           'steckverbinder_bnc.html',
  'SMA-Steckverbinder':                           'steckverbinder_sma.html',
  'Kabeldämpfung I':                              'kabeldaempfung_1.html',
  'Kabeldämpfung II':                             'kabeldaempfung_2.html',
  'Skineffekt':                                   'skineffekt.html',
  'Stehwellenverhältnis (SWR)':                   'swr.html',
  'Stehwellenverhältnis (SWR) II':                'swr_2.html',
  'Stehwellenverhältnis (SWR) III':               'swr_3.html',
  'Stehwellenmessgerät (SWR-Meter) I':            'swr_meter_1.html',
  'Stehwellenmessgerät (SWR-Meter) II':           'swr_meter_2.html',
  'Vektorieller Netzwerkanalysator (VNA) I':      'vna_1.html',
  'Vektorieller Netzwerkanalysator (VNA) II':     'vna_2.html',
  'Phasenverschiebung in Übertragungsleitungen':  'leitung_phasenverschiebung.html',
  'Impedanztransformation':                       'impedanztransformation.html',
  'Lecherleitung':                                'lecherleitung.html',
  'Mantelwellen I':                               'mantelwellen_1.html',
  'Mantelwellen II':                              'mantelwellen_2.html',
  'Umwegleitung':                                 'umwegleitung.html',

  // Personenschutzabstand
  'Personenschutz':                               'personenschutzabstand.html',
  'Effektive Strahlungsleistung (ERP) I':                         'effektive_strahlungsleistung_erp_1.html',
  'Äquivalente isotrope Strahlungsleistung (EIRP) I':             'aequivalente_isotrope_strahlungsleistung_eirp_1.html',
  'Äquivalente isotrope Strahlungsleistung (EIRP) II':            'aequivalente_isotrope_strahlungsleistung_eirp_2.html',
  'Effektive Strahlungsleistung (ERP) II':                        'effektive_strahlungsleistung_erp_2.html',
  'Sendeleistung Klasse N':                       'sendeleistung_klasse_n.html',
  'Anzeige ortsfester Amateurfunkanlagen':        'anzeige_ortsfester_amateurfunkanlagen.html',
  'Standortbescheinigung':                        'standortbescheinigung.html',
  'Personenschutzabstand II':                     'personenschutzabstand_2.html',
  'Personenschutzabstand III':                    'personenschutzabstand_3.html',
  'Näherungsformel I':                            'naeherungsformel_1.html',
  'Näherungsformel II':                           'naeherungsformel_2.html',
  'Nahfeld':                                      'nahfeld.html',
  'Personenschutz bei Richtantennen':             'personenschutzabstand_richtantennen.html',

  // Sicherheit
  'Öffnen elektrischer Geräte I':                 'elektrische_geaete_oeffnen_1.html',
  'Öffnen elektrischer Geräte II':                'elektrische_geaete_oeffnen_2.html',
  'Potentialausgleich und Blitzschutz':           'blitzschutz.html',
  'Schutzerdung und Potentialausgleich I':        'schutzerdung_1.html',
  'Schutzerdung und Potentialausgleich II':       'schutzerdung_2.html',
  'Blitzerdung':                                  'blitzerdung.html',
  'Statische Aufladung von Antennen':             'statische_aufladung.html',
  'Energieleitungen':                             'antennen_energieleitungen.html',
  'Baurecht und Haftung':                         'antennen_baurecht_haftung.html',
  'Berühren von Antennen I':                      'antennen_beruehrung_1.html',
  'Berühren von Antennen II':                     'antennen_beruehrung_2.html',
  'Aufenthalt im Strahlengang':                   'strahlengang_aufenthalt.html',

  // Gesetze und Vorschriften
  'Internationale Vereinbarungen, Gesetze und Vorschriften': 'gesetze_vorschriften.html',
  'Amateurfunkdienst':                            'amateurfunkdienst.html',
  'Amateurfunkstelle':                            'amateurfunkstelle.html',
  'Funkamateur':                                  'funkamateur.html',
  'Zulassung':                                    'zulassung.html',
  'Anschrift und Änderung':                       'anschrift.html',
  'Gebühren und Beiträge':                        'gebuehren_beitraege.html',
  'Fernmeldegeheimnis und Abhörverbot':           'fernmeldegeheimnis_abhoerverbot.html',
  'Verstöße und Folgen':                          'verstoesse_und_folgen.html',
};

String? subsectionUrl(String course, String subsectionTitle) {
  final slug = _subsectionSlugs[subsectionTitle];
  if (slug == null) return null;
  return 'https://50ohm.de/${course}_$slug';
}
