name: Build Flutter App from PR

on:
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:
  build:
    name: Build PR
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      #2 Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3 Install specified flutter version
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      #4 Install dependencies
      - name: Install Dependencies
        run: fvm flutter pub get

      #5 Updating licenses
      - name: fetching licenses
        run: fvm flutter pub run flutter_oss_licenses:generate.dart

      #6 Building APK
      - name: Build APK
        run: fvm flutter build apk --debug

      #7 Build iOS (ipa)
      - name: Build IPA
        run: fvm flutter build ios --no-codesign


      #8 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: build/ios/iphoneos/Runner.app
